version: "3.9"

# Define the Argments services APP to run

services:
  app:
    container_name: Django-dockerized
    build:
      context: .
      args:
        - DEV=true
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: always 
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
